---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
      solveButton: false
    - name: module-01
      label: "Using Ansible documentation"
      solveButton: false
    - name: module-02
      label: "Ansible Facts Playbook"
      solveButton: true
    - name: module-03
      label: "Using the Debug Module"
      solveButton: false

tabs:
  - name: "code-server"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel
    external: false
  - name: "TERMINAL"
    url: /wetty_vscode
