---
antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "create-network-backup-job"
      solveButton: true
    - name: module-02
      label: "create-survey"
      solveButton: true
    - name: module-03
      label: "execute-survey-job-template"
      solveButton: false

tabs:
  - name: "Ansible Automation Platform"
    url: https://controller-${guid}.${domain}/
    external: false
  - name: "TERMINAL"
    url: /wetty_controller
